(() => {
  // <stdin>
  console.log("This site was generated by Hugo.");
  document.addEventListener("DOMContentLoaded", init);
  function init() {
    setLogo();
    processTable();
    processFootnotes();
    processHeadings();
  }
  function processHeadings() {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        const id = entry.target.getAttribute("id");
        if (entry.intersectionRatio > 0) {
          document.querySelector(`nav li a[href="#${id}"]`).parentElement.classList.add("active");
        } else {
          document.querySelector(`nav li a[href="#${id}"]`).parentElement.classList.remove("active");
        }
      });
    });
    document.querySelectorAll(":is(h1, h2, h3, h4, h5, h6)[id]").forEach((section) => {
      observer.observe(section);
    });
  }
  function processFootnotes() {
    const footnoteRefs = document.querySelectorAll("a.footnote-ref");
    footnoteRefs.forEach((ref) => {
      const dialog = document.createElement("dialog");
      dialog.classList.add("footnote-popover");
      document.body.appendChild(dialog);
      dialog.popover = "auto";
      const id = ref.getAttribute("href").slice(4);
      console.log(id);
      ref.setAttribute("style", `--anchor-name: --fn-${id};`);
      const content = document.querySelector(`#fn\\:${id} > p`).cloneNode(true);
      dialog.appendChild(content);
      dialog.setAttribute("style", `--anchor: --fn-${id};`);
      const dialogenter = (ev) => {
        dialog.showPopover();
      };
      const dialogleave = (ev) => {
        dialog.hidePopover();
      };
      ref.addEventListener("mouseenter", (ev) => {
        dialog.showPopover();
        dialog.addEventListener("mouseenter", dialogenter, { once: true });
        dialog.addEventListener("mouseleave", dialogleave, { once: true });
      });
      ref.addEventListener("mouseleave", (ev) => {
        dialog.hidePopover();
      });
    });
  }
  function setLogo() {
    const logo = document.getElementById("logo");
    const src = `/logo-${Math.floor(Math.random() * 6) + 1}.svg`;
    console.log(src);
    logo.setAttribute("src", src);
  }
  function processTable() {
    const tables = document.querySelectorAll("table");
    tables.forEach((table) => {
      const wrapper = document.createElement("div");
      wrapper.classList.add("table-wrapper");
      table.parentElement.insertBefore(wrapper, table);
      wrapper.appendChild(table);
    });
  }
})();
