baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MeliPlug'
theme = 'meliplug'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 30

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 40


[markup]
  [markup.highlight]
  	noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
