baseURL = 'https://meliplug.info/'
languageCode = 'en-us'
title = 'MeliPlug.info'
theme = 'meliplug'
enableEmoji = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Ideas'
    pageRef = '/ideas'
    weight = 20

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30

  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 40

  # [[menus.main]]
  #   name = 'Tags'
  #   pageRef = '/tags'
  #   weight = 50



[markup]
  [markup.highlight]
  	noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      # hardWraps = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[security]
  enableInlineShortcodes = true
